// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPu9pmNZIuHm_ToL-Nb7SQdw56cg00Ww',
    appId: '1:839496357828:web:00cc058a1103d16e25f691',
    messagingSenderId: '839496357828',
    projectId: 'medicalapp-1cacd',
    authDomain: 'medicalapp-1cacd.firebaseapp.com',
    storageBucket: 'medicalapp-1cacd.firebasestorage.app',
    measurementId: 'G-L64TM48W4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7WmU9IcFlDIx9cMLiu2y-v_BWb50h-X4',
    appId: '1:839496357828:android:079014cf5b3f9ea025f691',
    messagingSenderId: '839496357828',
    projectId: 'medicalapp-1cacd',
    storageBucket: 'medicalapp-1cacd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBknwCt2BJ8gGCivSNJQNeWgwKrdNh9yUw',
    appId: '1:839496357828:ios:e656e45b00c0528e25f691',
    messagingSenderId: '839496357828',
    projectId: 'medicalapp-1cacd',
    storageBucket: 'medicalapp-1cacd.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBknwCt2BJ8gGCivSNJQNeWgwKrdNh9yUw',
    appId: '1:839496357828:ios:e656e45b00c0528e25f691',
    messagingSenderId: '839496357828',
    projectId: 'medicalapp-1cacd',
    storageBucket: 'medicalapp-1cacd.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfPu9pmNZIuHm_ToL-Nb7SQdw56cg00Ww',
    appId: '1:839496357828:web:193032ca635af2d125f691',
    messagingSenderId: '839496357828',
    projectId: 'medicalapp-1cacd',
    authDomain: 'medicalapp-1cacd.firebaseapp.com',
    storageBucket: 'medicalapp-1cacd.firebasestorage.app',
    measurementId: 'G-PKWHPHMGK6',
  );
}
